#ifndef _rock_states_h
#define _rock_states_h

#define GAMEPLAY_NOT_PLAYING 1
#define GAMEPLAY_COMM_TEST 2
#define GAMEPLAY_PLAYING 3
#define GAMEPLAY_TIMEOUT 4
#define GAMEPLAY_HALFTIME 5
#define GAMEPLAY_SCORED_GOAL 6
#define FIND_PUCK 7
#define MOVE_TO_PUCK 8
#define ALIGN_PUCK 9
#define CHECK_FOR_ASSIST_CHANCE 10
#define MOVE_TO_GOAL 11
#define RIGHT_GUIDE_TO_GOAL 12
#define LEFT_GUIDE_TO_GOAL 13
#define CHARGE_ENEMY_GOAL 14
#define SHOOT_PUCK 15
#define MOVE_PATROL 16
#define MOVE_TO_DEFENSE_PUCK_IN_SIGHT 17
#define MOVE_TO_DEFENSE_PUCK_OUT_OF_SIGHT 18
#define MOVE_AROUND_PERIMETER 19
#define GUARD_GOAL_PUCK_IN_SIGHT 20
#define GUARD_GOAL_PUCK_IN_CONTACT 21
#define GUARD_GOAL_PUCK_OUT_OF_SIGHT 22

#endif
