#ifndef _rock_states_h
#define _rock_states_h

#define GAMEPLAY_NOT_PLAYING 1
#define GAMEPLAY_COMM_TEST 2
#define GAMEPLAY_PLAY_COMMAND 3
#define GAMEPLAY_TIMEOUT 4
#define GAMEPLAY_HALFTIME 5
#define GAMEPLAY_SCORED_GOAL 6
#define FIND_PUCK 7
#define MOVE_TO_PUCK 8
#define ALIGN_PUCK 9
#define CHECK_FOR_ASSIST_CHANCE 10
#define CALL_FOR_ASSIST 11
#define ASSIST_BY_CLEARING_PATH 12
#define MOVE_TO_GOAL 13
#define RIGHT_GUIDE_TO_GOAL 14
#define LEFT_GUIDE_TO_GOAL 15
#define CHARGE_ENEMY_GOAL 16
#define SHOOT_PUCK 17
#define MOVE_PATROL 18
#define MOVE_TO_DEFENSE_PUCK_IN_SIGHT 19
#define MOVE_TO_DEFENSE_PUCK_OUT_OF_SIGHT 20
#define MOVE_AROUND_PERIMETER 21
#define GUARD_GOAL_PUCK_IN_SIGHT 22
#define GUARD_GOAL_PUCK_IN_CONTACT 23
#define GUARD_GOAL_PUCK_OUT_OF_SIGHT 24
#define GET_AGGRESSIVE 50
#define GO_BATSHIT_CRAZY 100

#endif
